blocks:
  - bin: 7
    offset: 0.02
  - bin: 6
    offset: 0.02
  - bin: 1
    offset: 0.02
  - bin: 6
    offset: 0.07
  - bin: 2
    offset: 0.02
  - bin: 8
    offset: 0.02
  - bin: 9
    offset: 0.02
  - bin: 4
    offset: 0.02
  - bin: 2
    offset: 0.07
  - bin: 7
    offset: 0.07
  - bin: 2
    offset: 0.12000000000000001
  - bin: 10
    offset: 0.02
  - bin: 8
    offset: 0.07
  - bin: 3
    offset: 0.02
  - bin: 8
    offset: 0.12000000000000001
  - bin: 7
    offset: 0.12000000000000001
  - bin: 9
    offset: 0.07
  - bin: 7
    offset: 0.17
  - bin: 10
    offset: 0.07
  - bin: 5
    offset: 0.02
  - bin: 4
    offset: 0.07
  - bin: 9
    offset: 0.12000000000000001
  - bin: 4
    offset: 0.12000000000000001
  - bin: 5
    offset: 0.07
  - bin: 11
    offset: 0
