blocks:
  - bin: 7
    offset: 0.030
  - bin: 6
    offset: 0.030
  - bin: 1
    offset: 0.030
  - bin: 6
    offset: 0.120
  - bin: 2
    offset: 0.030
  - bin: 8
    offset: 0.030
  - bin: 9
    offset: 0.030
  - bin: 4
    offset: 0.030
  - bin: 2
    offset: 0.120
  - bin: 7
    offset: 0.120
  - bin: 2
    offset: 0.210
  - bin: 10
    offset: 0.030
  - bin: 8
    offset: 0.120
  - bin: 3
    offset: 0.030
  - bin: 8
    offset: 0.210
  - bin: 7
    offset: 0.210
  - bin: 9
    offset: 0.120
  - bin: 7
    offset: 0.300
  - bin: 10
    offset: 0.120
  - bin: 5
    offset: 0.030
  - bin: 4
    offset: 0.120
  - bin: 9
    offset: 0.210
  - bin: 4
    offset: 0.210
  - bin: 5
    offset: 0.120
  - bin: 11
    offset: 0.000
